IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GETFORMS')
BEGIN
	DROP PROC GETFORMS
END

GO
create procedure GETFORMS
as
select * from FORM 
INNER JOIN CLIENTS on FORM.IDCLIENTS = CLIENTS.IDCLIENTS
INNER JOIN FROM_EMPLOYEES_LINK on FORM.idFORM = FROM_EMPLOYEES_LINK.idFORM
INNER JOIN EMPLOYEES on FROM_EMPLOYEES_LINK.IDEMPLOYEES = EMPLOYEES.IDEMPLOYEES
INNER JOIN FROM_PRODUCTS_LINK on FORM.idFORM = FROM_PRODUCTS_LINK.idFORM
INNER JOIN PRODUCT on FROM_PRODUCTS_LINK.idPRODUCT = PRODUCT.idPRODUCT
INNER JOIN FURNITURE_STORE on FORM.IDFURNITURE_STORE = FURNITURE_STORE.IDFURNITURE_STORE
