create procedure GETFORMS
as
select	FORM.IDFORM, FORM.DATE_ORDER, 
		PRODUCT.NAME AS PRODUCTNAME, PRODUCT.PRICE AS PRODUCTPRICE,
		CLIENTS.NAME AS CLIENTSNAME, CLIENTS.SURNAME AS CLIENTSSURNAME,
		EMPLOYEES.NAME AS EMPLOYEESNAME, EMPLOYEES.SURNAME AS EMPLOYEESURNAME,
		FURNITURE_STORE.REGION AS STOREREGION, FURNITURE_STORE.CITY AS STORECITY,
		PRODUCT.CITY AS MANUFACTURECITY
from FORM 
INNER JOIN CLIENTS on FORM.IDCLIENTS = CLIENTS.IDCLIENTS
INNER JOIN EMPLOYEES on FORM.IDEMPLOYEES = EMPLOYEES.IDEMPLOYEES
INNER JOIN PRODUCT on FORM.IDPRODUCT = PRODUCT.IDPRODUCT
INNER JOIN FURNITURE_STORE on FORM.IDFURNITURE_STORE = FURNITURE_STORE.IDFURNITURE_STORE


