USE TAXI_3_2;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GETFORMS')
BEGIN
	DROP PROC GETFORMS
END

GO
create procedure GETFORMS
as
select	*
from TRANSPORTATION 
INNER JOIN CLIENTS on TRANSPORTATION.IDCLIENTS = CLIENTS.IDCLIENTS
INNER JOIN TRANSPORTATION_WATER_LINK on TRANSPORTATION.idTRANSPORTATION = TRANSPORTATION_WATER_LINK.idTRANSPORTATION
INNER JOIN WATER on TRANSPORTATION_WATER_LINK.IDWATER = WATER.idWATER
INNER JOIN TRANSPORTATION_CAR_LINK on TRANSPORTATION.idTRANSPORTATION = TRANSPORTATION_CAR_LINK.idTRANSPORTATION
INNER JOIN CAR on TRANSPORTATION_CAR_LINK.IDCAR = CAR.IDCAR
INNER JOIN ROUTE on TRANSPORTATION.IDROUTE = ROUTE.IDROUTE
INNER JOIN MANUFACTURER on MANUFACTURER.IDMANUFACTURER = CAR.IDMANUFACTURER
