parent('Igor', 'Maryna').
parent('Igor', 'Viktor').
parent('Galyna', 'Maryna').
parent('Galyna', 'Viktor').
parent('Oleksandr', 'Taya').
parent('Oleksandr', 'Maryana').
parent('Nina', 'Taya').
parent('Nina', 'Maryana').
parent('Viktor', 'Stanislav').
parent('Viktor', 'Myroslav').
parent('Taya', 'Stanislav').
parent('Taya', 'Myroslav').
parent('Myroslav', 'Taras').
parent('Myroslav', 'Pavlo').
parent('Chrystyna', 'Taras').
parent('Chrystyna', 'Pavlo').
parent('Matvii', 'Chrystyna').
parent('Svitlana', 'Chrystyna').
